name: C++ CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Conan Installation ...
      run: |
        pip install conan==2.0.17
        conan profile detect

    - name: Install the requirements specified in a  conan recipe
      run: |
        conan install . --build missing -u
    
    - name: Installing dependencies and call the build() method.
      run: |
        conan build .

    - name: Creating a package directly from pre-compiled binaries.
      run: |
        conan export-pkg .
